version: '3.8'

services:
  database:
    image: postgres:17-alpine
    container_name: school
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/school
    depends_on:
      - database
    # The app will be available on localhost:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: school_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    # The frontend maps internal port 80 to external port 4200
    # Available on localhost:4200

volumes:
  postgres_data:
